apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: wordpress
type: Opaque
stringData:
  WORDPRESS_DB_USER: admin
  WORDPRESS_DB_PASSWORD: root123
  MYSQL_ROOT_PASSWORD: root123
